### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mariopo3** [Matsuneitor/Roulette#1]
![IMG-20210318-WA0011](https://user-images.githubusercontent.com/53239338/111698757-fb7e9600-8815-11eb-9802-dbd6c4ed85b9.jpg)
Me spamea ese error la consola, tenes idea de que puede ser?

**Comment by aematsubara** [comment]
Hola! Necesito el error entero, en texto si puede ser, ya que no puedo ver el stacktrace completo. Si puede ser el .log entero mejor.

Prueba también actualizando a la versión 5.1-SNAPSHOT del plugin.

Saludos

**Comment by mariopo3** [comment]
.... [19:46:23 WARN]: [Roulette] Task #8318168 for Roulette v5.1-SNAPSHOT generated an exception
java.lang.IllegalArgumentException: hologram already deleted
at com.gmail.filoghost.holographicdisplays.util.Validator.isTrue(Validator.java:27) ~[?:?]
at com.gmail.filoghost.holographicdisplays.object.CraftHologram.appendTextLine(CraftHologram.java:126) ~[?:?]
at com.gmail.filoghost.holographicdisplays.object.CraftHologram.appendTextLine(CraftHologram.java:37) ~[?:?]
at me.matsubara.roulette.game.Game.setupJoinHologram(Game.java:341) ~[?:?]
at me.matsubara.roulette.game.Game.createGamePart(Game.java:165) ~[?:?]
at me.matsubara.roulette.game.Game.access$000(Game.java:42) ~[?:?]
at me.matsubara.roulette.game.Game$1.run(Game.java:151) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Airplane-"e7fc41a"]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Airplane-"e7fc41a"]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1356) ~[patched_1.16.5.jar:git-Airplane-"e7fc41a"]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:381) ~[patched_1.16.5.jar:git-Airplane-"e7fc41a"]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1269) ~[patched_1.16.5.jar:git-Airplane-"e7fc41a"]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.5.jar:git-Airplane-"e7fc41a"]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Airplane-"e7fc41a"]
at java.lang.Thread.run(Thread.java:834) [?:?]
Ahi me esta pasando denuevo, creo que se produce cuando eliminas una mesa que no se terminó de crear

**Comment by aematsubara** [comment]
Si, debe ser por eso. Para la próxima actualización lo arreglare. Gracias por reportar
