### ISSUE TITLE
Armor stands didn't spawn when server restarting

### ISSUE THREAD

**Issue by iBuseWinner** [Matsuneitor/Roulette#2]
Server version: Yatopia 1.16.5
Roulette version: 5.1-SNAPSHOT

Gamemode spectator:
![image](https://user-images.githubusercontent.com/44753872/112304423-86481080-8cae-11eb-9f25-fa723ca779a3.png)

**Comment by aematsubara** [comment]
Hi!

Do you got any errors in console? I think the reason is because of Yatopia though,

Also, do that happen when creating a game?

**Comment by iBuseWinner** [comment]
Maybe this...
No errors on startup

`[10:08:34] [Server thread/WARN]: [Roulette] Task #6801873 for Roulette v5.1-SNAPSHOT generated an exception
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1493) ~[?:?]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1516) ~[?:?]
	at me.matsubara.roulette.runnable.Selecting.run(Selecting.java:38) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[1.16.5-patched.jar:git-Yatopia-staging/1.16.5-14]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[1.16.5-patched.jar:git-Yatopia-staging/1.16.5-14]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1383) ~[1.16.5-patched.jar:git-Yatopia-staging/1.16.5-14]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:397) ~[1.16.5-patched.jar:git-Yatopia-staging/1.16.5-14]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1292) ~[1.16.5-patched.jar:git-Yatopia-staging/1.16.5-14]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1015) ~[1.16.5-patched.jar:git-Yatopia-staging/1.16.5-14]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[1.16.5-patched.jar:git-Yatopia-staging/1.16.5-14]
	at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by aematsubara** [comment]
Hey, sorry for the late response,

That error has nothing to do with armorstands disappearing, but it's a error I've never seen, so thanks for reporting it.

About armor stands dissapearing, do they spawn when doing /roulette create?

**Comment by iBuseWinner** [comment]
Yes, they're spawning when admin use /roulette create

**Comment by iBuseWinner** [comment]
They stopped deleting after server restart...

**Comment by aematsubara** [comment]
Hey, I've been a bit busy lately

So, it's working now?

Some people reported the same error lately, so I'll be working on a fix asap

**Comment by aematsubara** [comment]
Should be fixed now, if not, I'll reopen this issue.

**Comment by aematsubara** [comment]
Reopening this since still happen; working on a fix.

**Comment by aematsubara** [comment]
Should be working now.
