### ISSUE TITLE
No se puede crear ningun juego con Roulette6.0

### ISSUE THREAD

**Issue by mariopo3** [Matsuneitor/Roulette#3]
[08:43:32] [Server thread/WARN]: [Roulette] Task #6409 for Roulette v6.0-SNAPSHOT generated an exception
java.lang.NullPointerException: null
	at me.matsubara.roulette.file.Games.saveGame(Games.java:233) ~[?:?]
	at me.matsubara.roulette.game.Game.createGamePart(Game.java:161) ~[?:?]
	at me.matsubara.roulette.game.Game.access$000(Game.java:42) ~[?:?]
	at me.matsubara.roulette.game.Game$1.run(Game.java:153) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Airplane-"e7fc41a"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Airplane-"e7fc41a"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1356) ~[patched_1.16.5.jar:git-Airplane-"e7fc41a"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:381) ~[patched_1.16.5.jar:git-Airplane-"e7fc41a"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1269) ~[patched_1.16.5.jar:git-Airplane-"e7fc41a"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.5.jar:git-Airplane-"e7fc41a"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Airplane-"e7fc41a"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Adjunto error, al instalarlo de 0 al plugin usando Airplane para la 1.16.5 y ejecutar el comando para crear una mesa, no se genera nada y la consola spamea el mensaje anterior

**Comment by aematsubara** [comment]
I'll fix it right now, thanks for reporting!

**Comment by aematsubara** [comment]
Puede ser que hayas borrado el archivo games.yml? Ya que es la unica manera en la que pueda ocurrir ese error.

**Comment by mariopo3** [comment]
No, no se generó directamente el archivo, tengo que crearlo?

**Comment by aematsubara** [comment]
Que raro, deberia de crearse automaticamente, proba de nuevo con la nueva version,

**Comment by mariopo3** [comment]
Estoy usando la ultima version e instalandolo de 0 y no lo genera, pero quizas la solucion sea generarlo yo mismo

**Comment by aematsubara** [comment]
Debería de estar arreglado en la siguiente actualización.
