### ISSUE TITLE
Error on table creation

### ISSUE THREAD

**Issue by CloudeLecaw** [Matsuneitor/Roulette#6]
There is an error if you try to create a table in roulete 6.2

The roulettfolder is generated new to make sure everything is in.
this happens on table creation
used command - **/roulette create TestTable Croupier american**
```
[22:20:37] [Server thread/WARN]: [Roulette] Task #31051 for Roulette v6.2-SNAPSHOT generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.file.FileConfiguration.set(String, Object)" because the return value of "me.matsubara.roulette.file.Games.getConfig()" is null
	at me.matsubara.roulette.file.Games.saveGame(Games.java:251) ~[?:?]
	at me.matsubara.roulette.game.Game.createGamePart(Game.java:193) ~[?:?]
	at me.matsubara.roulette.game.Game.access$000(Game.java:42) ~[?:?]
	at me.matsubara.roulette.game.Game$1.run(Game.java:185) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-641]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-641]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1423) ~[patched_1.16.5.jar:git-Paper-641]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.16.5.jar:git-Paper-641]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-641]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-641]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-641]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

The console gets spammed endless (logfile was pimped up to 20mb within 4 minutes, then i broke up)
![Snag_fc6c28b](https://user-images.githubusercontent.com/12080017/116929068-2dc94300-ac5e-11eb-942f-80679390b3db.png)

Citizens_2.0.27-Build2302
CMI_8.8.3.8

- No NPCLib
- No Holographic Display plugin (u wrote u can use CMI for it)

Note: When using Version 6.1 it seems to be fine...  So its an issue from Update 6.2

**Comment by aematsubara** [comment]
Thanks for reporting!

Can you try with the beta release, please?

https://github.com/Matsuneitor/Roulette/releases/tag/BETA-RELEASE

**Comment by CloudeLecaw** [comment]
give me 3 minutes i will give a try :)

**Comment by CloudeLecaw** [comment]
This Version did it. This fixed the issue =)

**Comment by CloudeLecaw** [comment]
Should i close this issue now? Your beta works well!

**Comment by aematsubara** [comment]
Yes, thanks. I'll update right now.
